### ISSUE TITLE
Function for obtaining UUID variant

### ISSUE THREAD

**Issue by purrgrammer** [47deg/memeid#1]
The variant indicates the layout of the UUID. The UUID specification covers one particular variant. Other variants are reserved or exist for backward compatibility reasons (e.g., for values assigned before the UUID specification was produced). An example of a UUID that is a different variant is the null UUID, which is a UUID that has all 128 bits set to zero.

In the canonical representation:

    xxxxxxxx-xxxx-xxxx-Nxxx-xxxxxxxxxxxx

the most significant bits of N indicate the variant (depending on the variant one, two, or three bits are used). The variant covered by the RFC4122 is indicated by the two most significant bits of N being 1 0 (i.e., the hexadecimal N will always be 8, 9, A, or B).

See https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#variant()

**Comment by gutiory** [comment]
PR => #15
